version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
      timezone: UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm
    groups:
      types:
        patterns:
          - '@types/*'
      eslint:
        patterns:
          - 'eslint'
          - '@eslint/*'
          - '@typescript-eslint/*'
          - 'typescript-eslint'
          - 'eslint-config-*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
      timezone: UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
